version: '3.1'

services:
  mongod:
    image: mongo
    volumes:
      - ./dbdata:/data/db
    ports:
      - 27017:27017
    container_name: mongod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
  webhook:
    image: webhook
    build: ./src/
    container_name: webhook
    restart: always
    environment:
      - MONGO_URI=mongodb://root:toor@mongod:27017
      - SPEND_SHELF_DB=spendShelf
    depends_on:
      - mongod
  lb:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
    ports:
      - 80:80
      - 443:443
    container_name: "lb"
    depends_on:
      - webhook