version: '3.1'

services:
  mongod:
    image: mongo
    volumes:
      - ./dbdata:/data/db
    ports:
      - 27017:27017
    container_name: mongod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SPENDSHELF_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${SPENDSHELF_MONGO_PASSW}
  spendshelf:
    image: spendshelf
    build: ./src/
    container_name: spendshelf
    restart: always
    environment:
      - HTTP_ADDR=:80
      - MONGO_URI=mongodb://${SPENDSHELF_MONGO_USER}:${SPENDSHELF_MONGO_PASSW}@mongod:27017
      - SPEND_SHELF_DB=spendShelf
      - GIN_MODE=release
    depends_on:
      - mongod
  lb:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
    ports:
      - 80:80
      - 443:443
    container_name: "lb"
    depends_on:
      - spendshelf