version: '3.1'

services:
  mongod:
    image: mongo
    volumes:
      - ./dbdata:/data/db
    ports:
      - 27017:27017
    container_name: mongod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SPENDSHELF_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${SPENDSHELF_MONGO_PASSW}
    labels:
      - "traefik.enable=false"
  spendshelf:
    image: spendshelf
    build: ./src/
    container_name: spendshelf
    restart: always
    environment:
      - HTTP_ADDR=:80
      - SPENDSHELF_MONGO_URI=mongodb://${SPENDSHELF_MONGO_USER}:${SPENDSHELF_MONGO_PASSW}@mongod:27017
      - SPEND_SHELF_DB=spendShelf
      - SPEND_SHELF_MONO_APIKEY=${SPEND_SHELF_MONO_APIKEY}
      - GIN_MODE=release
    depends_on:
      - mongod
    labels:
      - "traefik.http.routers.spendshelf.rule=PathPrefix(`/`)"
      - "traefik.http.services.spendshelf.loadbalancer.server.port=80"
  reverse-proxy:
    image: traefik:v2.1
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: "reverse-proxy"
    depends_on:
      - spendshelf