// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/lungria/spendshelf-backend/api"
	"github.com/lungria/spendshelf-backend/config"
	"github.com/lungria/spendshelf-backend/mono/importer"
	"github.com/lungria/spendshelf-backend/mono/importer/interval"
	"github.com/lungria/spendshelf-backend/storage"
)

// Injectors from wire.go:

func InitializeApp() (*State, error) {
	scheduler := NewSchedulerProvider()
	configConfig, err := config.FromEnv()
	if err != nil {
		return nil, err
	}
	client := NewMonoAPIProvider(configConfig)
	context := NewCtxProvider()
	pool, err := NewDbPoolProvider(context, configConfig)
	if err != nil {
		return nil, err
	}
	postgreSQLStorage := storage.NewPostgreSQLStorage(pool)
	generator := interval.NewIntervalGenerator(postgreSQLStorage)
	importerImporter := importer.NewImporter(client, postgreSQLStorage, generator)
	v := NewRoutesProvider()
	server := api.NewServer(configConfig, v...)
	state := NewAppStateProvider(scheduler, importerImporter, server, pool, configConfig)
	return state, nil
}
