// Code generated by mockery v1.0.0. DO NOT EDIT.

package webhooks

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// InsertOneHook provides a mock function with given fields: transaction
func (_m *MockRepository) InsertOneHook(transaction *WebHook) error {
	ret := _m.Called(transaction)

	var r0 error
	if rf, ok := ret.Get(0).(func(*WebHook) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
