name: Deploy (main)

on:
  push:
    branches: [ v2/ci-cd ]

jobs:   
  build:    
    runs-on: "ubuntu-20.04"
    env:
      DOCKER_REGISTRY: registry.hub.docker.com      
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}  
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

      # - name: Available platforms
      #   run: echo ${{ steps.buildx.outputs.platforms }}
    
      - name: Docker Login      
        if: success()      
        run: |        
          echo "${DOCKER_TOKEN}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
    
      - name: Docker Build & Push      
        if: success()      
        run: |        
          docker build \
          --platform linux/arm64/v8 \
          --tag suddengunter/spendshelf-backend:latest \
          --file ./Dockerfile \
          --output type=image,push=true .