name: Deploy (main)

on:
  push:
    branches: [ v2/ci-cd ]

jobs:   
  build:    
    runs-on: ubuntu-18.04    
      # env:      
      # DOCKER_REGISTRY: registry.hub.docker.com      
      # DOCKER_IMAGE: suddengunter/spendshelf-backend      
      # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      # DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}  
      # DOCKER_TARGET_PLATFORM: linux/arm/v8                    
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
 