name: main

on:
  push:
    branches: [ main ]

jobs:   
  build:    
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}  
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
    
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            TARGETOS:linux
            TARGETARCH:arm64
          platforms: linux/arm64
          push: true
          tags: suddengunter/spendshelf-backend:latest